language: java

jdk:
- oraclejdk8

after_success:
- .buildscript/deploy_snapshot.sh

env:
  global:
  - secure: kpyRlNeuwdsFh2bUbHg7PLVIfFEQ2xwoVIKWNwwblfNsoKOzF1g0JaCRDQdN6ozbHwvg21Vwy/YUcPY/fTrHBLASletUUmWWMQRuM/1pmnFeWq7YaCx7pwPoCEUMaWpVe3320lBfS1bw8/8N+hKuua3hUgrop7givdjnfia2iodfZvBfMiJ+ReEaL+yny9iV2vLYfksbzfeDWHdGwj/ewIEgJnUY2GQSKYTdcqRW0dsdOn35cC4sfufoMlekVv5rZO9iJPcxRHjyjCUzg3JVLXpKSxD9QJI2KlEM35Uqy9YugaHQJPKg5YMrDwgY0XkCWAKqoL+q0DQtWR/UsP5xQDv4XOflZBIv6GMRLDmx4TYPH/Pm6++YSUK2b1tsJUlIxz3MoOBS34aPmc/lV4vB2hTdwgAYsA9ncI44nOE3EL8zOA0usG076e0O/6rfJGN3YSEjRjf+PuD7bg/Bvhsgj3821hK6182IePTAsBTGkImy2vOlDE1OqdQCmG2rZQKFXSUSUO0A6fISogSE/PeUlf+wuDzM4Sbt30az1mnQfWn4Okq+KPPewoc5Bkoehjcx+UUNjtOGo1EEplYCeixYEtk14GSWnvSDZyNItXKzGVHESyKJ7hnbZzm3CDBAIC4zxKMp3dVciQJXS6UArCXN37TqyQovKEkjKhy4ZVkZCi0=
  - secure: kkSPpKHSaxqxeam44J+QGqtbhRLRLbuj37+rdn6ZI172qhQ1sXBnOx/hcCA4IzVNrd/bpFVTbudSkDVyvPUhyRE05l54UnclQ3oQ9iKyxHNCG8X67L9OugUTj3XJxheVyj8aX72zpXTm/wI4cjBuFmGm7y1KoH79a9moKHQdJTrtQc5vItmgbSoifZAgO3qqy5Pgx0An1VZ/LfyE8L1Di/3GsoNoTdKeSOu7nl8QFhG18rH7q4E77IqKj/4uxuoMQoDnGK+qdCRFLv4AfFRmr/+yywMAMvRKga/6g0wzEWUgadZgJqm14Ymrgo3Uo20BlyVg45esFwqRn1eYju8ngF9rSFaVwLl2jnOWfXhmUdIHhuf/rVFJHGI9rVm7sG97W04Wa9M5+ZCn5Y9E8gzIeutLTM7jwsbg1+fc974j5nxs7Bzq9fuUfwhoRa2vk1RptHega8ORGlqsB4oeeLgnNp1oXt3I/+78Y52GIJg/ZYIE77IL7vlcrvOZZ4M9084K2Slu3b4gkLy6ojicx1JCRXaALe/UDXWf7yMkgSzQ3hitjCzO/6ozUeyZFZSd3acJcLnwl8fBQXsgaMWWcvkEIOMWH4koiIoqiWYSmiYKz9N3JVSbobPnf3QMFHUsTjypjknJ5zQHaYd/NhE2TQtbgc50a4Ye9CJFEOkjBarxU9s=

notifications:
  email: false

sudo: false

cache:
  directories:
  - "$HOME/.m2"
